### ISSUE TITLE
Build error on docker image

### ISSUE THREAD

**Issue by hhashim2** [Fraunhofer-SIT/charra#41]
Following errors when CHARRA docker image is built:

```
src/util/coap_util.c: In function 'charra_coap_new_request':
src/util/coap_util.c:105:7: error: 'coap_pdu_t' {aka 'struct coap_pdu_t'} has no member named 'tid'; did you mean 'mid'?
  105 |  pdu->tid = msg_id;
      |       ^~~
      |       mid
```

**Comment by eckelmeckel** [comment]
Hi @hhashim2,

Thanks for pointing that out. I need to check whether it has changed in libcoap. TID should be the Token ID. MID is the Message ID. CoAp RFC7252 states "(Note that the Token is a concept separate from the Message ID.)" (https://tools.ietf.org/html/rfc7252).

It appears that in libcoap "tid" changed to "mid".

The problem is that we need the develop branch of libcoap, otherwise we would not be able to use block handling. So, there is no stable libcoap dependency at the moment, except referencing a commit.

I am working in that.

Thanks,
Michael

**Comment by eckelmeckel** [comment]
According to my colleague, @DominikLorych, with commit ae752e9e7aa611ba476f11ff763b4ae57b0a7cce of
libcoap it works. Just FYI, in case a quick fix is needed.
